name: 'Set PowerShell Manifest Version'
description: 'Set the version number in a PowerShell module''s manifest file'
inputs:
  manifest-path:
    description: 'Relative path to manifest'
    required: true
  major:
    description: 'Major Version'
    required: false
    default: -1
  minor:
    description: 'Minor Version'
    required: false
    default: -1
  build:
    description: 'Build Number'
    required: false
    default: -1
  revision:
    description: 'Optional Revsion Number'
    required: false
    default: -1
runs:
  using: 'composite'
  steps:
    - run: |
        gci env:
      shell: pwsh
    - run: |
        echo "Build is ${{ inputs.build }}"
        ${{ github.action_path }}/Update-ManifestVersion.ps1 `
            -ManifestPath (Join-Path $env:GITHUB_WORKSPACE ${{ inputs.manifest-path }}) `
            -Major ${{ inputs.major }} `
            -Minor ${{ inputs.minor }} `
            -Build ${{ inputs.build }} `
            -Revision ${{ inputs.revision }} `
            -Verbose
      shell: pwsh

branding:
  icon: 'terminal'
  color: 'blue'