name: 'Set PowerShell Manifest Version'
description: 'Set the version number in a PowerShell module''s manifest file'
author: Seekatar
inputs:
  manifest-path:
    description: 'Relative path to manifest'
    required: true
  major:
    description: 'Major Version, defaults to value in manifest'
    required: false
    default: '-1'
  minor:
    description: 'Minor Version, defaults to value in manifest'
    required: false
    default: '-1'
  build:
    description: 'Build Number, usually use github.run_number'
    required: false
    default: '-1'
  revision:
    description: 'Optional Revision Number'
    required: false
    default: '-1'
  prerelease:
    description: 'Optional Prerelease value'
    required: false
    default: ''
  commitSHA:
    description: 'Optional commitSHA to save in PrivateData'
    required: false
    default: ''
  githubRef:
    description: 'Instead of other parameters, use ref with version as last level'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - run: |
        if ('${{ inputs.githubRef }}') {
          ${{ github.action_path }}/Update-ManifestVersion.ps1 `
              -ManifestPath (Join-Path $env:GITHUB_WORKSPACE ${{ inputs.manifest-path }}) `
              -GitHubRef '${{ inputs.githubRef }}' `
              -CommitSHA '${{ inputs.commitSHA }}'
        } else {
          ${{ github.action_path }}/Update-ManifestVersion.ps1 `
              -ManifestPath (Join-Path $env:GITHUB_WORKSPACE ${{ inputs.manifest-path }}) `
              -Major ${{ inputs.major }} `
              -Minor ${{ inputs.minor }} `
              -Build ${{ inputs.build }} `
              -Revision ${{ inputs.revision }} `
              -Prerelease '${{ inputs.prerelease }}' `
              -CommitSHA '${{ inputs.commitSHA }}'
        }
      shell: pwsh

branding:
  icon: 'terminal'
  color: 'blue'