# This is a basic workflow to help you get started with Actions

name: PesterTest

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    # The type of runner that the job will run on
    runs-on: ${{matrix.os}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run a one-line script
        shell: pwsh
        run: echo ${GITHUB_RUN_NUMBER}

      - name: Run Pester Tests
        shell: pwsh
        run: |
          Install-Module Pester -Confirm:$False -Force
          $result = Invoke-Pester -PassThru
          $result.tests | select name,result
          if ($result.Result -ne "Passed") {
            Write-Error "Pester tests failed"
          }
